### ISSUE TITLE
Bug: IBAN validator dictionaty has duplicate entry for 'CR'

### ISSUE THREAD

**Issue by teaVeloper** [malicialab/iocsearcher#4]
When running the code through my linter (ruff) it told me, that the IBAN dictionary has the key 'CR' duplicated.

I looked up, I think it should only have the value '21' and not the second of '22' (maybe it was meant for another country code and got mistyped?)

The errors are in `searcher.py` on line 460 (the correct entry) and line 469 (the supposedly wrong one).

**Comment by malicialab** [comment]
Thanks for the report. Indeed the key should not be duplicated. According to this webpage the correct length for Costa Rica (CR) is 22, not 21
https://www.iban.com/structure
I fixed that entry and also added a bunch of countries that were missing

I have released a 1.0.2 iocsearcher package that should fix this. If the fix looks good to you, please close this issue, otherwise let me know.

**Comment by teaVeloper** [comment]
hey,

thanks for the quick reply! My bad I thought (after quick search) 'CR' would be Croatia.

I will close, the issue :)
